version: '2'

services: 



  atg-downloader-client:
    image: node:boron
    container_name: atg-downloader-client
    volumes:
      - ./:/src/app
    working_dir: /src/app
    command: sh -c 'npm install; npm run build;'
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: 'production'
  
  proxy-server:
    image: node:boron
    container_name: proxy-server
    volumes:
      - ./proxy-server:/src/app
    working_dir: /src/app
    command: sh -c 'npm install; npm start;'
    ports: 
      - '3002:3002'

  api-server:
    image: node:boron
    container_name: api-server
    volumes:
      - ./:/src/app
    working_dir: /src/app
    command: sh -c 'npm install; npm run server;'
    ports: 
      - '3001:3001'
    environment:
      NODE_ENV: 'production'